name: Bandit Security Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '40 17 * * 3'  # Executa semanalmente às 17:40 (UTC) nas quartas-feiras

jobs:
  bandit:
    name: Executar análise com Bandit
    runs-on: ubuntu-latest

    permissions:
      contents: read           # Necessário para ações básicas
      security-events: write  # Para envio de resultados no formato SARIF (futuramente, se quiser)
      actions: read           # Para repositórios privados

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Executar Bandit
        run: |
          bandit -r app -ll -ii
