name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test-security:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src  # Garante que src é raiz para imports absolutos
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências do projeto
        run: |
          pip install pip-tools
          pip-sync requirements-dev.txt

      - name: Instalar pacote em modo editável
        run: pip install -e .

      - name: Lint (flake8 e pylint)
        run: |
          flake8 src/htmlreader src/tests
          pylint src/htmlreader || true

      - name: Segurança (bandit)
        run: bandit -r src/htmlreader

      - name: Testes com cobertura
        run: pytest --cov=src/htmlreader src/tests --maxfail=1 --disable-warnings -v

      - name: Gerar relatório de cobertura
        run: coverage xml

      - name: Upload cobertura para Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
        continue-on-error: true
