name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pip-tools
          pip-sync requirements-dev.txt

      - name: Lint (flake8)
        run: flake8 app/ tests/

      - name: Security Check (bandit)
        run: bandit -r app/

      - name: Run Tests with Coverage
        run: pytest --cov=app tests/
